title: UVA Degrees 
author:
  name: William Kaiser
  email: wkaisertexas@gmail.com

description: > 
  Google Sheets templates for tracking degree progress at the University of Virginia (UVA)

theme: minima
google_analytics: G-M8BB9MS7XE
plugins:
  - jekyll-seo-tag

minima:
  - { platform: github,         user_url: "https://www.github.com/wkaisertexas" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/williamdkaiser" }